### ISSUE TITLE
correção nova extranet

### ISSUE THREAD

**Issue by eltonchrls** [codhab/management#18]
### tasks ###

- [ ] Alteração de Agendamento - Elton
- [ ] página de troca de senha - Victor
- [ ] permissões - Bruno
- [ ] listagem deficientes e idosos - Igor
